spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/orion_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:orion_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:orion_pass}
spring.datasource.driver-class-name=org.postgresql.Driver