spring.datasource.url=${ORACLE_DATASOURCE_URL:jdbc:oracle:thin:@localhost:1521/XEPDB1}
spring.datasource.username=${ORACLE_DATASOURCE_USERNAME:rm565568}
spring.datasource.password=${ORACLE_DATASOURCE_PASSWORD:fiap2026}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver